#!/bin/sh -eu

cd "$HOME" || exit 1

# see if an HDMI connected screen is connected. if it is, turn off laptop screen
# PHYSETUP: 0=laptop 1=desktop
if xrandr | grep -qF 'HDMI1 connected'; then
	xrandr --output eDP1 --off
	xset s "$((20 * 60))" "$((20 * 60))"
	xautolock -time 20 -locker lock-screen &
	unclutter --timeout 2 --jitter 50 &
	PHYSETUP=1
else
	xrandr --output eDP1 --mode '1280x720'
	xset s "$((10 * 60))" "$((10 * 60))"
	xautolock -time 10 -locker lock-screen &
	unclutter --timeout 2 --jitter 100 &
	PHYSETUP=0
fi
export PHYSETUP

if ! pgrep pulseaudio 1>/dev/null; then
	pulseaudio --start --log-target=file:"$LOGD/pulseaudio"
fi
dunst &
unclutter --timeout 1 &

exec i3
