[[ $- =~ i ]] || return

set -o vi
shopt -s autocd
shopt -s checkwinsize
shopt -s cmdhist
shopt -s histappend
stty stop ''
ulimit -c 1000

bind '"\C-l":clear-screen'

HISTCONTROL='ignoredups'
HISTFILE=~/.bashhist
HISTSIZE=-1

if [ "$(id -u)" -eq 0 ]; then
	PS1='#$?: '
else
	PS1='\$$?: '
fi

. /etc/bashfc
. /etc/aliasrc
