set nocompatible
set mouse=
set shortmess=aI
set formatoptions=crql
set cmdheight=2
set tabstop=4
set shiftwidth=4
set laststatus=0

let g:cmdmd='!'
let g:cmdfl='~/.nvimcmd/cmd'

hi NonText ctermfg=gray
hi Error ctermfg=white ctermbg=black
hi ErrorMsg ctermfg=white ctermbg=black
hi Search ctermfg=none ctermbg=none

function ChCmdMd()
	if g:cmdmd == '!'
		let g:cmdmd='term'
	else
		let g:cmdmd='!'
	endif
	echo 'cmdmd='.g:cmdmd
endfunction

function ClFl()
	%s/[ 	]\+$//ge
endfunction

map <C-q> :qa!<nl>
map <C-d> :w \| exe cmdfl' %'<nl>
map <C-z> :u<nl>
nnoremap <C-s> :call ClFl() \| w<nl>
nnoremap <C-x> :q<nl>
nnoremap <C-l> :bn<nl>
nnoremap <C-h> :bp<nl>
nnoremap <C-j> 5j
nnoremap <C-k> 5k
nnoremap - :exe 'e' cmdfl<nl>
nnoremap _ :let cmdfl='~/.nvimcmd/'.input('cmdfl: ')<nl>
nnoremap = :call ChCmdMd()<nl>
inoremap <C-s> <Esc>
vnoremap <C-s> <Esc>

if !empty($DISPLAY)
	nnoremap <F1> :%w !clipb<nl><nl>
	nnoremap <C-c> :.w !clipb<nl><nl>
	inoremap <C-c> <Esc>:.w !clipb<nl><insert>
	vnoremap <C-c> y<nl>:call system('clipb', @0)<nl>
endif

autocmd BufNewFile,BufRead ~/.nvimcmd/*
	\ nnoremap <buffer> - :w \| bd<nl> |
	\ map <buffer> <C-d> <NOP>
