set nocompatible
set autoindent
set ttymouse=""
set mouse=""
set shortmess=aI
set formatoptions=crql
set cmdheight=2
set tabstop=4
set shiftwidth=4

let enpager=1
let vimdir=$HOME.'/.vim'
let cmdfl=vimdir.'/cmd'
let bkupdir=vimdir.'/bkup'

if !isdirectory(vimdir)
	echo '[WRN]: vimdir nexist'
	exec '!mkdir -p '.vimdir
endif
if !isdirectory(bkupdir)
	echo '[WRN]: bkupdir nexist'
	exec '!mkdir -p '.bkupdir
endif

function ExecCmdFl()
	silent !clear
	if g:enpager == 1
		exec '!'.g:cmdfl.' % 2>&1 | $PAGER'
	else
		exec '!'.g:cmdfl.' %'
	endif
endfunction

function ChEnPager()
	if g:enpager == 1
		let g:enpager = 0
	else
		let g:enpager = 1
	endif
	echo 'enpager = '.g:enpager
endfunction

function Paste()
	set paste
	r !clipb -o
	set nopaste
endfunction

function Bkup()
	exec '!cp % '.g:bkupdir.'/%_'.localtime()
endfunction

nmap <C-q> :qa!<nl>
nmap <C-x> :q<nl>
nmap <C-d> :w \| call ExecCmdFl()<nl><nl>
nmap <C-z> :u<nl>
nmap K :bn<nl>
nmap J :bp<nl>
nmap <C-f> 10jzz
nmap <C-b> 10kzz
nmap - :exec 'e '.cmdfl<nl>
nmap _ :let cmdfl=
nmap = :call ChEnPager()<nl>

nmap <C-s> :%s/[ 	]\+$//ge \| w<nl>
imap <C-s> <Esc>
vmap <C-s> <Esc>

vmap <C-z> <NOP>
omap <C-z> <NOP>

if !empty($DISPLAY)
	nmap <F1> :%w !clipb<nl><nl>
	nmap <C-c> :.w !clipb<nl><nl>
	imap <C-c> <Esc>:.w !clipb<nl><insert>
	vmap <C-c> y<nl>:call system('clipb', @0)<nl>
else
	nmap <C-c> <NOP>
endif

autocmd BufNewFile,BufRead * {
	if expand('%') == g:cmdfl
		nmap <buffer> - :w \| bd<nl>
		map <buffer> <C-d> <NOP>
	endif
}

hi clear NonText
hi clear Error
hi clear ErrorMsg
hi clear Search

if filereadable('./lvimrc')
	source ./lvimrc
endif
