set nocompatible
set autoindent
set ttymouse=""
set mouse=""
set shortmess=aI
set formatoptions=crql
set cmdheight=2
set tabstop=4
set shiftwidth=4

let enablepager=1
let vimdir=$HOME.'/.vim'
let bkupdir=vimdir.'/bkup'

if !isdirectory(vimdir)
	echo '[WRN]: vimdir nexist'
	exec '!mkdir -p '.vimdir
endif
if !isdirectory(bkupdir)
	echo '[WRN]: bkupdir nexist'
	exec '!mkdir -p '.bkupdir
endif

function ExecCmdFl()
	!clear
	if g:enablepager == 1
		exec '!'.g:vimdir.'/cmd % 2>&1 | $PAGER'
	else
		exec '!'.g:vimdir.'/cmd %'
	endif
endfunction

function Paste()
	set paste
	r !clipb -o
	set nopaste
endfunction

function Bkup()
	exec '!cp % '.g:bkupdir.'/%_'.localtime()
endfunction

nmap <C-q> :qa!<nl>
nmap <C-x> :q<nl>
nmap <C-d> :w \| call ExecCmdFl()<nl><nl>
nmap <C-s> :%s/[ 	]\+$//ge \| w<nl>
nmap <C-z> :u<nl>
nmap K :bn<nl>
nmap J :bp<nl>
nmap <C-f> 10jzz
nmap <C-b> 10kzz
nmap - :e ~/.vim/cmd<nl>
nmap = :let enablepager=1<nl>
nmap + :let enablepager=0<nl>

imap <C-s> <Esc>

vmap <C-s> <Esc>
vmap <C-z> <NOP>

if !empty($DISPLAY)
	nmap <F1> :%w !clipb<nl><nl>
	nmap <C-c> :.w !clipb<nl><nl>
	imap <C-c> <Esc>:.w !clipb<nl><insert>
	vmap <C-c> y<nl>:call system('clipb', @0)<nl>
else
	nmap <C-c> <NOP>
endif

autocmd BufNewFile,BufRead ~/.vim/cmd {
	nmap <buffer> - :w \| bd<nl>
	map <buffer> <C-d> <NOP>
}

hi clear NonText
hi clear Error
hi clear ErrorMsg
hi clear Search
