#!/bin/sh -eu

cd "$HOME" || exit 1

startproc(){
	local CMD="${1%% *}"
	command -v "$CMD" 1>/dev/null || exit 2
	if ! pgrep -f "$CMD" 1>/dev/null; then
		$@ &
	fi
}

# see if an HDMI connected screen is connected.
# if it is, turn off laptop screen.
if xrandr | grep -qF 'HDMI1 connected'; then
	SECS="$((20 * 60))"
	xrandr --output eDP1 --off
	xset s $SECS $SECS
	startproc xautolock -time 20 -locker xlock
	PHYSETUP=desktop
else
	SECS="$((10 * 60))"
	xrandr --output eDP1 --mode '1600x900'
	xset s $SECS $SECS
	startproc xautolock -time 10 -locker xlock
	PHYSETUP=laptop
fi
export PHYSETUP

startproc unclutter -idle 1 -grab
startproc dunst -config $HOME/.dunstrc
dwm
