#!/bin/sh

set -eu

[ "$#" -eq 0 ] && exit 1

DIRS='/usr/local/mbin /home/lancia/.lsr/mbin'

for file in "$@"; do

	FILE_NAME="$(basename "$file")"

	for dir in $DIRS; do

		TARGET_FILE="$dir/$FILE_NAME"

		[ ! -e "$TARGET_FILE" ] && continue

		if [ "$TARGET_FILE" = "$file" ]; then

			echo "Error: $TARGET_FILE and $file are the same, skipping..."

			continue

		elif [ -e "$TARGET_FILE" ] && ! diff -q "$TARGET_FILE" "$file"; then

			diff "$TARGET_FILE" "$file" || continue

		else

			echo "no difference between $TARGET_FILE and $file"

		fi

	done

done
