#!/bin/sh

set -eu

#BRIDGE,ClientTransportPlugin obfs4 exec /usr/bin/obfs4proxy
#BRIDGE,
#BRIDGE,UseBridges 1
#BRIDGE,
#BRIDGE,Bridge obfs4 188.166.188.252:9452 10DDAB52625BDE5AB053473F6A9C621F63803821 cert=m7h9aZYEtMMowtTppLu1+DqPs879YVaTUuByotHnExRa5wgIrmQl4RFNJ+jcWiPK5+jfLw iat-mode=0
#BRIDGE,Bridge obfs4 223.204.71.200:50993 A341D8F041C140BB91969145D4399F6B666EF1CF cert=m8wN7dxqjGTshPqGSJo73T/WA8/IOzP/Qy8exNimXVsMKP036CfKZ2VprgxYIb5ErBV7fA iat-mode=0
#BRIDGE,Bridge obfs4 65.108.182.58:8429 6C8264BD4C03CC2FAC80B7C73D2D76D44AB5BB96 cert=ObtoZ3SurzSYEykD3OuHy9RwZgcUukHdCMj1N8t3zhxPsYg8dv91JzSUc6Rr0ma/z4TsNw iat-mode=0


COMMENT_IDENTIFIER='#BRIDGE,'


if [ "$1" = 'enable' ]; then

	sed -i "s/^$COMMENT_IDENTIFIER//" /etc/tor/torrc

elif [ "$1" = 'disable' ]; then

	sed -i "s/^Bridge obfs4/${COMMENT_IDENTIFIER}Bridge obfs4/;\
		s/^UseBridges/${COMMENT_IDENTIFIER}UseBridges/;\
		s/^ClientTransportPlugin/${COMMENT_IDENTIFIER}ClientTransportPlugin/" /etc/tor/torrc

fi
