#!/bin/sh

set -e

case "$1" in

	primary-tor) exec chromium --proxy-server="socks5://$(tpsel)" ;;

	secondary-tor)

		DIR="$HOME/.config/chromium.tor"

		[ ! -e "$DIR" ] && exit 1

		chromium --proxy-server="socks5://$(tpsel)" --user-data-dir="$DIR"

	;;

	*) exit 1 ;;

esac
