#!/bin/sh

set -eu

alias print='notify-send'

INPUT="$HOME"

cd "$INPUT"

while true; do

	INPUT="$(find . -mindepth 1 -maxdepth 1 \( -type d -or -type f \) | sort | dmenu -p "$PWD")"

	[ "$INPUT" = '..' ] && cd .. && continue

	[ -d "$INPUT" ] && cd "$INPUT" && continue

	case "$INPUT" in

		sh) exec st ;;

		thunar) exec thunar ;;

		*.[pP][dD][fF]) exec mupdf "$INPUT" ;;

		*.m[kp][v4]) exec mpv "$INPUT" ;;

		*.od[gpt]) exec libreoffice "$INPUT" ;;

		*)
			if [ ! -d "$INPUT" ] && [ ! -f "$INPUT" ]; then

				print "Error: \"$INPUT\" is neither a file nor a directory"

			elif file "$INPUT" | grep -F 'ASCII'; then

				exec env st vim "$INPUT"

			else

				print 'Error: program not defined for this file'

			fi

		;;

	esac

done
