#!/bin/sh

set -eu

INPUT="$(dmenu < /dev/null)"

[ -z "$INPUT" ] && exit 0

COMMAND="$(echo "$INPUT" | cut -d' ' -f1)"

if ! which "$COMMAND" 1>/dev/null; then

	notify-send "Error: command $COMMAND not found"

	exit 1

fi

OUTPUT="$(eval $INPUT)" || {

	echo "Error executing command $INPUT"

	exit 1

}

notify-send "$OUTPUT"
