#!/bin/sh

set -eu

COMMAND="$(dmenu < /dev/null)"

[ -z "$COMMAND" ] && exit 0

PROGRAM="$(echo "$COMMAND" | cut -d' ' -f1)"

if ! which "$PROGRAM" 1>/dev/null 2>&1; then

	notify-send "Error: command $PROGRAM not found"

	exit 1

fi

OUTPUT="$(eval $COMMAND 2>&1)" || {

	notify-send "$(printf "Error executing command \"%s\", output:\n%s" "$COMMAND" "$OUTPUT")"

	exit 1

}

notify-send "$OUTPUT"
