#!/bin/sh

set -eu

COMMAND="$(dmenu < /dev/null)"

[ -z "$COMMAND" ] && exit 0

EXE="$(echo "$COMMAND" | cut -d' ' -f1)"

if ! which "$EXE" 1>/dev/null; then

	notify-send "Error: command $EXE not found"

	exit 1

fi

[ -n "$*" ] && [ "$1" = '--with-output' ] && exec notify-send "$($COMMAND)"

exec $COMMAND
