#!/bin/sh


BACKUP_DIR="$HOME/.backup/tars"

HELP="USAGE: $0 [ directories to take a tar.gz backup of and put them in $BACKUP_DIR ]"

[ "$#" -eq 0 ] && printf 'Error: no arguments provided\n%s\n' "$HELP" && exit 1

for arg in "$@"; do

	if [ ! -d "$arg" ]; then

		printf 'Error: %s is not a directory\n%s\n' "$arg" "$HELP"

		exit 1

	fi

done

[ ! -e "$BACKUP_DIR" ] && mkdir -p "$BACKUP_DIR"

DATE="$(date '+%Y-%m-%d_%H-%M-%S')"

for dir in "$@"; do

	FULL_PATH="$(readlink -f "$dir")"

	echo "Backing up $FULL_PATH"

	DIR_NAME="$(basename "$FULL_PATH")"

	FILE_NAME="$(echo "$FULL_PATH" | sed -e 's/\//_/g' -e 's/\./_DOT_/g')"

	PARENT_DIR="$(dirname "$FULL_PATH")"

	tar czvf "${BACKUP_DIR}/${FILE_NAME}_${DATE}.tar.gz" -C "$PARENT_DIR" "./$DIR_NAME"

done
