#!/bin/sh

set -eu

[ "$#" -eq 0 ] && exit 1

DIRS='/usr/local/umbin /home/lancia/.lsr/lmbin'

EXIT_CODE=0

for file in "$@"; do

	[ ! -f "$file" ] && continue

	FILE_NAME="$(basename "$file")"

	for dir in $DIRS; do

		TARGET_FILE="$dir/$FILE_NAME"

		[ ! -e "$TARGET_FILE" ] && continue

		if [ "$TARGET_FILE" = "$file" ]; then

			echo "Error: $TARGET_FILE and $file are the same, skipping..."

			continue

		else

			if head -n1 "$file" | grep -q '^#!'; then

				OUTPUT="$(diff "$TARGET_FILE" "$file")" || {

					echo "---- $TARGET_FILE $file ----"

					echo "$OUTPUT"

					EXIT_CODE=1

				}

			fi

		fi

	done

done

exit "$EXIT_CODE"
