#!/bin/sh -eu

[ "$#" -eq 0 ] && exit 1

DIRS='/etc /usr/local/umbin /home/lancia/.lsr/lmbin /etc/init.d /usr/local/etc'
EXIT_CODE=0

for file in "$@"; do

	[ ! -f "$file" ] && continue

	FILENAME="${file##*/}"
	COUNTER=0

	for dir in $DIRS; do

		[ -e "$dir/$FILENAME" ] && COUNTER="$((COUNTER + 1))"

	done

	[ "$COUNTER" -eq 0 ] && continue

	if [ "$COUNTER" -gt 1 ]; then

		TARGET_FILE="$dir/$FILENAME"

		echo "---- Warning! file \"$file\" exists in multiple locations:"

		for dir in $DIRS; do

			[ -e "$dir/$FILENAME" ] && echo "$dir/$FILENAME"

		done

	fi

	for dir in $DIRS; do

		TARGET_FILE="$dir/$FILENAME"
		[ ! -e "$TARGET_FILE" ] && continue

		if [ "$TARGET_FILE" = "$file" ]; then

			echo "Error: $TARGET_FILE and $file are the same, skipping..." 1>&2
			continue

		else

			OUTPUT="$(diff "$TARGET_FILE" "$file")" || {

				echo "---- $TARGET_FILE $file ----"
				echo "$OUTPUT"
				EXIT_CODE=1

			}

		fi

	done

done

exit "$EXIT_CODE"
