#!/bin/sh -eu

. /usr/local/subr/io.subr

[ "$#" -eq 0 ] && exit 1

DIRS='/etc /usr/local/umbin /home/lancia/.lsr/lmbin /etc/init.d /usr/local/etc /usr/local/subr'
EXIT_CODE=0
FILENAME=''

diff_files()
{
	OUTPUT="$(diff "$1" "$2")" || {

		echo "---- $1 $2 ----"
		echo "$OUTPUT"
		[ "$EXIT_CODE" -ne 1 ] && EXIT_CODE=1

	}
}


for file in "$@"; do

	[ ! -f "$file" ] && continue

	if grep -q "^$(readlink -f "$file"):" /letc/global-filelist; then
		diff_files "$(cut -d':' -f1 /letc/global-filelist)" "$(cut -d':' -f2 /letc/global-filelist)"
		continue
	fi

	FILENAME="${file##*/}"

	for dir in $DIRS; do

		TARGET_FILE="$dir/$FILENAME"
		[ ! -e "$TARGET_FILE" ] && continue
		if [ "$TARGET_FILE" = "$file" ]; then
			print_warning "$TARGET_FILE and $file are the same, skipping..."
			continue
		else

			diff_files "$file" "$TARGET_FILE"

		fi

	done

done

exit "$EXIT_CODE"
