#!/bin/sh -eu

[ "$#" -ne 1 ] && exit 1

. /usr/local/subr/io.subr

BLKID_OUTPUT="$(blkid)"
if echo "$BLKID_OUTPUT" | grep -F "$1" 1>/dev/null; then

	echo "$BLKID_OUTPUT" | grep -F "$1" | cut -d':' -f1

else

	print_error "UUID \"$1\" not found"
	exit 3

fi
