#!/bin/sh

set -eu

print_error() { echo "${0##*/}: Error: $1" ; }

FILE="$HOME/.tasks"
TASK_ID='t:'
CATEGORY_ID='c:'
NUM=''
OUTPUT=''

OUTPUT="$(sort "$FILE" | uniq -cd)" && [ -n "$OUTPUT" ] && {
	print_error 'there are duplicate categories in the tasks file, remove it:'
	echo "$OUTPUT"
	exit 1
}

grep -m1 -qvE "^($TASK_ID|$CATEGORY_ID)" "$FILE" && {
	print_error 'bad file, clean it'
	exit 1
}

[ "$#" -eq 0 ] && exit 1

case "$1" in

	a|a,t)
		NUM="$(grep -n "${CATEGORY_ID}$2" "$FILE" | cut -d':' -f1)" 

		[ -z "$NUM" ] && {
			print_error "category \"$2\" not found"
			exit 1
		}

		sed -i "${NUM}a ${TASK_ID}$3" "$FILE"
	;;

	a,c)
		grep -q "${TASK_ID}$2" "$FILE" && {
			print_error "category \"$2\" already exists"
			exit 1
		}

		echo "${TASK_ID}$2" >> "$FILE"
	;;

	l)
		NUM="$(grep -n "${CATEGORY_ID}$2" "$FILE" | cut -d':' -f1)" 

		[ -z "$NUM" ] && {
			print_error "category \"$2\" not found"
			exit 1
		}

		i="$NUM"
		while true; do
			i="$((i+1))"
			OUTPUT="$(sed -n "${i}p" "$FILE")"
			echo "$OUTPUT" | grep -q "^${CATEGORY_ID}" && break
			echo "$OUTPUT" | sed "s/^${TASK_ID}//"
		done

	;;

	*) print_error "argument \"$1\" not recongnized" && exit 1 ;;

esac
