#!/bin/sh

set -eu

print_error() { echo "${0##*/}: Error: $1" ; }

needed_number_of_args()
{
	[ "$#" -lt "$1" ] && {
		print_error "need at least $1 argument(s)"
		exit 1
	}
}

FILE="$HOME/.tasks"
TASK_ID='t:'
CATEGORY_ID='c:'
RESERVED_CATEGORY_KEYWORDS='all'
NUM=''
OUTPUT=''

if [ ! -e "$FILE" ]; then

	touch "$FILE"

else

	for keyword in $RESERVED_CATEGORY_KEYWORDS; do
		OUTPUT="$(grep "^${CATEGORY_ID}$keyword" "$FILE")" && {
			print_error 'reserved keywords used as categories in:'
			echo "$OUTPUT"
			exit 1
		}
	done
	
	OUTPUT="$(sort "$FILE" | uniq -cd)" && [ -n "$OUTPUT" ] && {
		print_error 'there are duplicate categories in the tasks file, remove it:'
		echo "$OUTPUT"
		exit 1
	}
	
	grep -m1 -qvE "^($TASK_ID|$CATEGORY_ID)" "$FILE" && {
		print_error 'file contains something other than what is allowed'
		exit 1
	}

fi

[ "$#" -eq 0 ] && exit 1

case "$1" in

	a|a,t)
		needed_number_of_args 3

		NUM="$(grep -n "${CATEGORY_ID}$2" "$FILE" | cut -d':' -f1)"

		[ -z "$NUM" ] && {
			print_error "category \"$2\" not found"
			exit 1
		}

		sed -i "${NUM}a ${TASK_ID}$3" "$FILE"
	;;

	a,c)
		needed_number_of_args 2

		grep -q "${TASK_ID}$2" "$FILE" && {
			print_error "category \"$2\" already exists"
			exit 1
		}

		echo "${TASK_ID}$2" >> "$FILE"
	;;

	l|l,c)
		needed_number_of_args 2

		[ "$2" = 'all' ] && exec sed "s/^${TASK_ID}//; s/^${CATEGORY_ID}/---/" "$FILE"

		NUM="$(grep -n "${CATEGORY_ID}$2" "$FILE" | cut -d':' -f1)"

		[ -z "$NUM" ] && {
			print_error "category \"$2\" not found"
			exit 1
		}

		i="$NUM"
		while true; do
			i="$((i+1))"
			OUTPUT="$(sed -n "${i}p" "$FILE")"
			echo "$OUTPUT" | grep -qv "^${TASK_ID}" && break
			echo "$OUTPUT" | sed "s/^${TASK_ID}//"
		done

	;;

	*) print_error "argument \"$1\" not recongnized" && exit 1 ;;

esac
