#!/bin/sh

set -eu

DIR="$HOME/Downloads"
PDF_DIR="$DIR/PDFs"
COMPRESSED_DIR="$DIR/compressed"
TORRENT_FILES_DIR="$DIR/torrent-files"
APK_FOLER="$DIR/apps"
PICS_FOLDER="$DIR/pics"

# $1: filename ending pattern, $2: the directory to move the files into
move_files()
{
	DESTINATION_DIR="$2"
	[ ! -e "$DESTINATION_DIR" ] && mkdir -p "$DESTINATION_DIR"

	for pattern in $1; do
		find "$DIR" -maxdepth 1 -mindepth 1 -type f -iname "*$pattern" | while read -r file; do
			FILENAME="$(basename "$file")"
			if [ -e "$DESTINATION_DIR/$FILENAME" ]; then
				for i in $(seq 1 1000); do
					[ -e "$DESTINATION_DIR/${FILENAME}.${i}" ] && continue
					FILENAME="${FILENAME}.${i}" && break
				done
			fi
			mv "$file" "$DESTINATION_DIR/$FILENAME"
		done
	done
}

while true; do
	sleep 10s
	# check if nobody has anything open in $DIR, then proceed
	lsof -u "$USER" | grep -qF "$(readlink -f "$DIR")" && continue
	move_files '.jpeg .jpg .png' "$PICS_FOLDER"
	move_files '.gz .zip .rar .xz' "$COMPRESSED_DIR"
	move_files '.pdf' "$PDF_DIR"
	move_files '.torrent' "$TORRENT_FILES_DIR"
	move_files '.apk' "$APK_FOLER"
done
