#!/bin/sh -eu

# $1: filename ending pattern, $2: the directory in $HOME/Downloads to move the files into
move_files()
{
	DESTINATION_DIR="$HOME/Downloads/$2"
	[ ! -e "$DESTINATION_DIR" ] && mkdir -p "$DESTINATION_DIR"

	for pattern in $1; do
		find "$HOME/Downloads" -maxdepth 1 -mindepth 1 -type f -iname "*$pattern" | while read -r file; do
			FILENAME="${FILENAME##*/}"
			if [ -e "$DESTINATION_DIR/$FILENAME" ]; then
				for i in $(seq 1 1000); do
					[ -e "$DESTINATION_DIR/${FILENAME}.${i}" ] && continue
					FILENAME="${FILENAME}.${i}" && break
				done
			fi
			mv "$file" "$DESTINATION_DIR/$FILENAME"
		done
	done
}

while true; do
	sleep 10s
	# check if nobody has anything open in $HOME/Downloads, then proceed
	lsof -u "$USER" | grep -qF "$(readlink -f "$HOME/Downloads")" && continue
	move_files '.jpeg .jpg .png' 'pics'
	move_files '.gz .zip .rar .xz' 'compressed'
	move_files '.pdf' 'PDFs'
	move_files '.torrent' 'torrent-files'
	move_files '.apk' 'apps'
	move_files '.txt' 'txt'
	move_files '.iso' 'iso'
	move_files '.diff' 'diffs'
	move_files '.docx' 'docx'
done
