#!/bin/sh -eu

[ "$#" -eq 0 ] && exit 1

OPTIONS=''; URL=''

for arg in "$@"; do
	case "$arg" in
		*youtube.com*) URL="$arg" ;;
		--mp3) OPTIONS='--extract-audio --audio-format mp3 --audio-quality 0' ;;
		*) exit 2 ;;
	esac
done

eval exec youtube-dl "$OPTIONS" "$URL"
