#!/bin/sh -e
. /usr/subr/out
[ "$#" -eq 0 ] && exit 1
DIR='/usr/bbx'
[ -e $DIR ] || {
	pwarn "$DIR no exist, creating it"
	mkdir $DIR
}
for arg in "$@"; do
	busybox "$arg" < /dev/null || {
		perr "$arg is not a valid bbx command"
		exit "$?"
	}
done
for arg in "$@"; do
	ln -s ../bin/busybox $DIR/"$arg"
done
