#!/bin/sh -e
. /usr/subr/out
[ "$#" -eq 0 ] && exit 1
DIR='/usr/bbx'
[ -e $DIR ] || {
	pwarn "$DIR no exist, creating it"
	mkdir $DIR
}
ALLCOMMS="$(busybox | awk '/Currently defined functions/,/EOF/' | sed 1d | sed 's/[ 	]//g' | tr ',' '\n' | sed '/^$/d')"
for arg in "$@"; do
	if [ -e "$DIR/$arg" ]; then
		perr "$arg already exists in $DIR"
		exit 1
	elif ! echo "$ALLCOMMS" | grep -q "^$arg\$"; then
		perr "$arg is not a valid bbx command"
		exit 2
	fi
done
for arg in "$@"; do
	ln -s ../bin/busybox $DIR/"$arg"
done
