#!/bin/sh -e

if [ "$1" = '--reinstall-grub' ]; then
	if ! mount | grep -q '^/dev/[^ ]\+ on /boot/efi'; then
		echo '[ERR]: /boot/efi not mounted' 2>&1
		exit 1
	fi
	rm -r /boot/efi/*
	grub-install --target=x86_64-efi --efi-directory=/boot/efi \
		--bootloader-id=ARTIX
fi

mkinitcpio -P && grub-mkconfig -o /boot/grub/grub.cfg
