#!/bin/sh -eu

[ "$(id -u)" -ne 0 ] && exit 1

. /usr/local/subr/io.subr

CONF_DIR='/etc/wpa_supplicant'
SSID=''
PASSWORD=''

read -r -p 'SSID: ' SSID

CONF_FILE="$CONF_DIR/$SSID.conf"

if [ -e "$CONF_FILE" ]; then
	print_error "there is already a file named $SSID.conf in $CONF_DIR"
	exit 1
fi

stty -echo
read -r -p 'Password: ' PASSWORD
echo
stty echo

cat <<EOF >"$CONF_FILE" && echo "File created at $CONF_FILE"
network={
        ssid="$SSID"
        key_mgmt=WPA-PSK
        psk="$PASSWORD"
}
EOF
