#!/bin/sh -eu
[ "$#" -eq 0 ] && exit 1
. /usr/subr/out
readonly D='/etc /usr/local/umbin /home/lancia/.lsr/lmbin /etc/init.d /usr/local/etc /usr/subr'
E=0
O=''
V=0
if [ "$#" -eq 1 ]; then
	V=1
else
	for arg in "$@"; do
		[ "$arg" = '-v' ] && V=1
		break
	done
fi
diff_files() {
	if [ "$V" -eq 1 ]; then
		echo "$1 > $2" | sed 's|/mnt/storage/encrypted|/home|g'
		O="$(diff "$1" "$2")" || {
			echo "$O"
			[ "$E" -ne 1 ] && E=1
		}
	else
		diff -q "$1" "$2" 1>/dev/null || echo "$1 != $2"
	fi
}
for file in "$@"; do
	[ ! -f "$file" ] && continue
	O="$(grep -m1 "^$(readlink -f "$file"):" /letc/swfl)" && {
		diff_files "$(echo "$O" | cut -d':' -f1)" "$(echo "$O" | cut -d':' -f2)"
		continue
	}
	for dir in $D; do
		TARGETF="$dir/${file##*/}"
		[ ! -e "$TARGETF" ] && continue
		diff_files "$file" "$TARGETF"
	done
done
exit "$E"
