#!/bin/sh -eu

[ "$#" -eq 0 ] && exit 1

. /usr/local/subr/out.subr

readonly DIRS='/etc /usr/local/umbin /home/lancia/.lsr/lmbin /etc/init.d /usr/local/etc /usr/local/subr'
EXIT=0
OUT=''
VERBOSE=0

if [ "$#" -eq 1 ]; then
	VERBOSE=1
else
	for arg in "$@"; do
		[ "$arg" = '-v' ] && VERBOSE=1
		break
	done
fi

diff_files()
{
	if [ "$VERBOSE" -eq 1 ]; then
		echo "($1 -- $2)" | sed 's|/mnt/storage/encrypted|/home|g'
		OUT="$(diff "$1" "$2")" || {
			echo "$OUT"
			[ "$EXIT" -ne 1 ] && EXIT=1
		}
	else
		diff -q "$1" "$2" 1>/dev/null || echo "$1" -- "$2"
	fi
}

for file in "$@"; do

	[ ! -f "$file" ] && continue

	OUT="$(grep -m1 "^$(readlink -f "$file"):" /letc/global-filelist)" && {
		diff_files "$(echo "$OUT" | cut -d':' -f1)" "$(echo "$OUT" | cut -d':' -f2)"
		continue
	}

	for dir in $DIRS; do

		TARGETF="$dir/${file##*/}"
		[ ! -e "$TARGETF" ] && continue
		diff_files "$file" "$TARGETF"

	done

done

exit "$EXIT"
