#!/bin/sh -eu

[ "$#" -ne 3 ] && {
	echo "USAGE: ${0##*/} [source file] [target] [perm]" 1>&2
	exit 1
}
[ "$(id -u)" -ne 0 ] && exit 2

exec echo "$(readlink -f "$1"):$(readlink -f "$2"):$3" >> /letc/swfl
