#!/bin/sh -eu

for file in "$@"; do
	[ ! -f "$file" ] && exit 1
done

case "${0##*/}" in
	li) TARGET_DIR='/home/lancia/.lsr/lmbin'; PERM=0755 ;;
	ui) TARGET_DIR='/usr/local/umbin'; PERM=0755 ;;
	si) TARGET_DIR='/usr/local/subr'; PERM=0644 ;;
	eii) TARGET_DIR='/etc/init.d'; PERM=0755 ;;
	*) exit 2 ;;
esac

for file in "$@"; do
	echo "$file --> $TARGET_DIR/$file"
	install -m "$PERM" "$file" "$TARGET_DIR"
done
