#!/bin/sh -eu

[ "$#" -gt 1 ] && exit 1

. /usr/local/subr/out.subr

if [ "$PROG_NAME" != 'poweroff' ] && [ "$PROG_NAME" != 'reboot' ]; then
	exit 2
fi

WHO_OUTPUT="$(who)"
echo "$WHO_OUTPUT" | cut -d' ' -f1 | grep -Fvq "$USER" && {
	perr "somebody else is logged in, cannot poweroff:"
	echo "$WHO_OUTPUT"
	exit 3
}

[ "$#" -eq 1 ] && case "$1" in
	-f|--force) exec loginctl "$PROG_NAME";;
	*) exit 4 ;;
esac

pgrep Xorg 1>/dev/null && {
	perr "an Xorg session is already running, cannot $PROG_NAME"
	exit 5
}

loginctl "$PROG_NAME"
