#!/bin/sh -e
O="$(pacman -Qq)"
tar -O -xf "$1" .PKGINFO | grep ^optdepend | sed 's/^optdepend = //' | while read -r pkg; do
	if echo "$O" | grep -q "$pkg"; then
		printf "%s [I]\n" "$pkg"
	else
		echo "$pkg"
	fi
done
