#!/bin/sh -e
. /usr/subr/out
[ "$#" -eq 0 ] && exit 1
O="$(pacman -Qq)"
CACHE="$(grep -o '^CacheDir.*$' /etc/pacman.conf | grep -o '/.*$')" || {
	CACHE=/var/cache/pacman/pkg/
}
for pkg in "$@"; do
	if [ ! -e "$pkg" ]; then
		if ! echo "$O" | grep -q "^$pkg$"; then
			perr "$pkg: pkg not found"
			exit 3
		fi
	pkg="$(find "$CACHE" -name "$pkg*" | tail -n1)"
	fi
	tar -O -xf "$pkg" .PKGINFO | grep ^optdepend | \
		sed 's/^optdepend = //' | while read -r optdep; do
			if echo "$O" | grep -q "^$(echo "$optdep" | cut -d':' -f1)$"; then
				printf "%s [I]\n" "$optdep"
			else
				echo "$optdep"
			fi
	done
done
