#!/bin/sh -e
if ! mount | grep -q '^/dev/[^ ]\+ on /boot/efi'; then
	exit 1
fi
TMP="$(mktemp -d)"
mv /boot/efi/* "$TMP"
grub-install --target=x86_64-efi --efi-directory=/boot/efi \
	--bootloader-id=ARTIX
rm -r "$TMP"
