#!/bin/sh

set -eu

[ "$(id -u)" -ne 0 ] && exit 1
[ "$#" -eq 0 ] && exit 1

PROGRAM_NAME="$(basename "$0")"

print_error() { echo "$PROGRAM_NAME: Error: $1" 1>&2 ; }

for command in "$@"; do

	EXE="${command%% *}"

	command -v "$EXE" 1>/dev/null || {
		print_error "command \"$EXE\" not found"
		continue
	}

	eval nohup "$command" 0<&- 1>/dev/null 2>&1 &

done
