#!/bin/sh

set -eu

[ "$(id -u)" -ne 0 ] && exit 1
[ "$#" -eq 0 ] && exit 1

PROGRAM_NAME="$(basename "$0")"

print_error() { echo "$PROGRAM_NAME: Error: $1" 1>&2 ; }

for arg in "$@"; do

	COMMAND="${arg%% *}"

	COMM_OUTPUT="$(command -v "$COMMAND")" || {
		print_error "command \"$COMMAND\" not found"
		continue
	}
	[ ! -f "$COMM_OUTPUT" ] && {
		print_error "command \"$COMMAND\" must be a regular file in the filesystem"
		continue
	}

	eval nohup "$arg" 0<&- 1>/dev/null 2>&1 &

done
