#!/bin/sh -eu

[ "$#" -eq 0 ] && exit 1

. /usr/local/subr/io.subr

COMMAND="${1%% *}"

COMM_OUTPUT="$(command -v "$COMMAND")" || {
	print_error "command \"$COMMAND\" not found"
	continue
}
[ ! -f "$COMM_OUTPUT" ] && {
	print_error "command \"$COMMAND\" must be a regular file in the filesystem"
	continue
}

eval exec nohup "$@" 0<&- 1>/dev/null 2>&1 &
