#!/bin/sh -eu

LAPTOP_RESOLUTION='1366 768'
DESKTOP_RESOLUTION='1920 1080'

set_resolution() { exec fbset -xres "${1## *}" -yres "${1##* }" ; }

if tty | grep -Eq '^/dev/(tty|console)'; then

	setfont /usr/share/kbd/consolefonts/LatGrkCyr-12x22.psfu.gz
	if [ "$#" -eq 1 ] && [ "$1" = '--laptop-resolution' ]; then
		set_resolution "$LAPTOP_RESOLUTION"
	elif fbset | grep -qF "geometry $LAPTOP_RESOLUTION $DESKTOP_RESOLUTION"; then
		set_resolution "$DESKTOP_RESOLUTION"
	fi

fi
