#!/bin/sh -eu

[ "$(id -u)" -ne 0 ] && exit 1
[ "$#" -eq 0 ] && exit 2
for arg in "$@"; do
	[ ! -d "$arg" ] && exit 3
done

WAREHOUSE='/mnt/warehouse'
BACKUP_DIR="$WAREHOUSE/backup"
[ ! -e "$BACKUP_DIR" ] && mkdir "$BACKUP_DIR"

if mount | grep -qF "on $WAREHOUSE"; then

	for arg in "$@"; do
		NAME="$(echo "$arg" | sed 's|/|_|g')"
		tar cpzf "$BACKUP_DIR/$NAME-$(date '+%Y-%m-%d.%H-%M-%S').tar.gz" -C "$arg" .
	done

else

	exit 3

fi
