#!/bin/sh -eu
[ "$(id -u)" -ne 0 ] && exit 1
. /usr/subr/out
CONFD='/etc/wpa_supplicant'
SSID=''
PASSWORD=''
read -r -p 'SSID: ' SSID
CONF="$CONFD/$SSID.conf"
[ -e "$CONF" ] && {
	perr "there is already a file named $SSID.conf in $CONFD"
	exit 2
}
stty -echo
read -r -p 'Password: ' PASSWORD
echo
stty echo
cat <<EOF >"$CONF"
network={
        ssid="$SSID"
        key_mgmt=WPA-PSK
        psk="$PASSWORD"
}
EOF
