#!/bin/sh -eu
. /usr/subr/o
if [ "$#" -ne 1 ]; then
	perrex 'need git commit mssg' 1
elif [ ! -e PKGBUILD ]; then
	perrex 'PKGBUILD nfound' 2
elif [ ! -e .gitignore ]; then
	pwrn '.gitignore file not found'
fi
FILES='PKGBUILD .SRCINFO'
for optfile in .gitignore .install; do
	[ -e "$optfile" ] && FILES="$FILES $optfile"
done
makepkg --printsrcinfo > .SRCINFO
git add $FILES
git commit -m "$1"
git push
