#!/bin/sh -eu
[ "$#" -eq 0 ] && exit 1
. /usr/subr/o
SED_REMOVE_ENDING_SPACE_PATTERN='s/ \+$//'
BASE_DEVEL_PKGS="$(pacman -Sg base-devel | cut -d' ' -f2 | tr '\n' ' ' | sed "$SED_REMOVE_ENDING_SPACE_PATTERN")"
BASE_DEVEL_PKGS="$BASE_DEVEL_PKGS awk roff yacc"
PRINT_FILENAME='false'
[ "$#" -gt 1 ] && PRINT_FILENAME='true'
for pkgbuild in "$@"; do
	MAKEDEPENDS_ARRAY="$(grep '^makedepends=' "$pkgbuild" | tr '\n' ' ' | sed -e 's/makedepends=//' -e "s/[()'\"]//g" -e "$SED_REMOVE_ENDING_SPACE_PATTERN")"
	[ -z "$MAKEDEPENDS_ARRAY" ] && {
		perr "makedepends array not found in file \"$pkgbuild\""
		continue
	}
	[ "$PRINT_FILENAME" = 'true' ] && echo "analysing file: $pkgbuild"
	for base_devel_pkg in $BASE_DEVEL_PKGS; do
		for makedepends_array_pkg in $MAKEDEPENDS_ARRAY; do
			[ "$base_devel_pkg" = "$makedepends_array_pkg" ] && echo "found redundant package: $base_devel_pkg"
		done
	done
done
