#!/bin/bash -eu

[ "$#" -eq 0 ] && exit 1

. /usr/local/subr/download.subr
. /usr/local/subr/html.subr

OUT=''

for word in "$@"; do

	word="${word/[).]/}"
	OUT="$(fast_curl "https://google.com/search?q=${word}+significado" | extract_class 'YrbPuc' '' | sed -n -e 's/&#183;/./; 1p')"
	[ -z "$OUT" ] && OUT='[ERROR]'
	printf '%s: %s\n' "$word" "$OUT"

done
