#!/bin/bash -eu

[ "$#" -eq 0 ] && exit 1

. /usr/local/subr/download.subr
. /usr/local/subr/html.subr

OUTPUT=''

for word in "$@"; do

	word="${word/./}"
	OUTPUT="$(fast_curl "https://google.com/search?q=${word}+significado" | extract_class 'YrbPuc' '' | head -n1)"
	[ -z "$OUTPUT" ] && OUTPUT='[ERROR]'
	printf '%s: %s\n' "$word" "$OUTPUT"

done
