#!/bin/bash -eu

[ "$#" -eq 0 ] && exit 1

. /usr/local/subr/download.subr
. /usr/local/subr/html.subr

CURL_OUTPUT=''

for word in "$@"; do

	word="${word/./}"

	CURL_OUTPUT="$(curl_command "https://dictionary.cambridge.org/dictionary/spanish-english/${word}")"
	[ -z "$CURL_OUTPUT" ] && echo "- $word: [ERROR]" && continue
	echo "- $word"

	printf '%s meaning: \n%s\n' '--' "$(extract_class 'trans dtrans' -m3 <<< "$CURL_OUTPUT" | uniq | sed 's/^/@ /')"

	printf '%s syntaxis: \n%s\n' '--' "$(extract_class '(pos dpos|gc dgc)' '' <<< "$CURL_OUTPUT" | sort | uniq | sed 's/^/@ /')"

done
