#!/bin/bash -eu

[ "$#" -eq 0 ] && exit 1

. /usr/local/subr/download.subr
. /usr/local/subr/html.subr

CURL_OUTPUT=''

print()
{
	printf '%s %s: \n%s\n' '--' "$1" "$(extract_class "$2" "$3" <<< "$CURL_OUTPUT" | sort | uniq | sed 's/^/@ /')"
}

for word in "$@"; do

	word="${word/./}"
	CURL_OUTPUT="$(curl_command "https://dictionary.cambridge.org/dictionary/spanish-english/${word}")"
	if ! [[ "$CURL_OUTPUT" =~ "$word" ]]; then
		echo "- $word: [ERROR]"
		continue
	fi

	echo "- $word"
	print 'meaning' 'trans dtrans' -m3
	print 'syntaxis' '(pos dpos|gc dgc)' ''
	print 'antonym' 'x-h dx-h' -m1

done
