#!/bin/sh -u

[ "$#" -eq 0 ] && exit 1

SINTAXIS_CLASS_KEYWORD='YrbPuc'
OUTPUT=''
CURL_OUTPUT=''

curl_command(){ curl --silent --user-agent "$USER_AGENT" --location "https://google.com/search?q=$1+significado" ; }
print_failure(){ echo "$1" 1>&2 ; }
grep_class(){ grep -o "class=\"$1\">[^<]\+" ; }

if [ "$#" -eq 1 ]; then

	CURL_OUTPUT="$(curl_command "$1")"
	[ -z "$CURL_OUTPUT" ] && print_failure "[CURL FAILURE]" && exit 1
	
	OUTPUT="$(echo "$CURL_OUTPUT" | grep_class "$SINTAXIS_CLASS_KEYWORD")"
	[ -z "$OUTPUT" ] && print_failure "[GREP FAILURE]" && exit 2
	
	echo "$OUTPUT" | sed -e 's/[^>]*>//' -e 's/&#183;/./g'

else

	for word in "$@"; do

		CURL_OUTPUT="$(curl_command "$word")"
		[ -z "$CURL_OUTPUT" ] && print_failure "$word: [CURL FAILURE]" && continue
		
		OUTPUT="$(echo "$CURL_OUTPUT" | grep_class "$SINTAXIS_CLASS_KEYWORD")"
		[ -z "$OUTPUT" ] && print_failure "$word: [GREP FAILURE]" && continue
		
		echo -n "$word: "
		echo "$OUTPUT" | sed -e 's/[^>]*>//' -e 's/&#183;/./g'

	done	

fi
