#!/bin/sh -u

[ "$#" -eq 0 ] && exit 1

. /usr/local/subr/html.subr

SINTAXIS_CLASS_KEYWORD='YrbPuc'
OUTPUT=''
CURL_OUTPUT=''

curl_command(){ curl --silent --user-agent "$USER_AGENT" --location "https://google.com/search?q=$1+significado" ; }

if [ "$#" -eq 1 ]; then

	CURL_OUTPUT="$(curl_command "$1")"
	extract_class "$CURL_OUTPUT" "$SINTAXIS_CLASS_KEYWORD"

else

	for word in "$@"; do

		CURL_OUTPUT="$(curl_command "$word")"
		extract_class "$CURL_OUTPUT" "$SINTAXIS_CLASS_KEYWORD"

	done

fi
