#!/bin/bash -eu

[ "$#" -eq 0 ] && exit 1

. /usr/local/subr/download.subr
. /usr/local/subr/html.subr

O=''
P='(verb-(translation|pronoun|entry verb-(normal|irregular|orto)))'
NP=0

for option in "$@"; do
	[ "$option" = '--np' ] && {
		P='(verb-(translation|entry verb-(normal|irregular|orto)))'
		NP=1
		break
	}
done

for w in "$@"; do

	[[ "$w" =~ ^- ]] && continue
	w="${w/./}"
	[[ "$w" =~ ^[a-z-]+/ ]] || w="present-tense/$w"

	O="$(fast_curl "https://www.spanishconjugation.net/${w}/")"
	[[ "$O" =~ 'Nothing Found' ]] && {
		echo '[ERROR]'
	}

	O="$(extract_class "$P" '' <<< "$O")"
	echo -n "@${w##*/}: "
	[ $NP -eq 1 ] && {
		echo "$O"
		continue
	}
	awk 'BEGIN { i=1 }\
		{ if(i==1){ printf("%s\n",$0); i=0; } else { printf("%s ",$0); i++; } }' <<< "$O"

done
