#!/bin/bash -eu

[ "$#" -eq 0 ] && exit 1

. /usr/local/subr/download.subr
. /usr/local/subr/html.subr

OUT=''
CLASS_PATTERN='(verb-(translation|pronoun|entry verb-(normal|irregular|orto)))'
NO_PRONOUNS=0

for option in "$@"; do
	[ "$option" = '--np' ] && {
		CLASS_PATTERN='(verb-(translation|entry verb-(normal|irregular|orto)))'
		NO_PRONOUNS=1
		break
	}
done

for word in "$@"; do

	[[ "$word" =~ ^- ]] && continue
	word="${word/./}"
	[[ "$word" =~ ^[a-z-]+/ ]] || word="present-tense/$word"

	OUT="$(fast_curl "https://www.spanishconjugation.net/${word}/")"
	[[ "$OUT" =~ 'Nothing Found' ]] && {
		echo '[ERROR]'
	}

	OUT="$(extract_class "$CLASS_PATTERN" '' <<< "$OUT")"
	echo -n "@${word##*/}: "
	[ $NO_PRONOUNS -eq 1 ] && {
		echo "$OUT"
		continue
	}
	awk 'BEGIN { i=1 }\
		{ if(i==1){ printf("%s\n",$0); i=0; } else { printf("%s ",$0); i++; } }' <<< "$OUT"

done
