#!/bin/bash -eu

[ "$#" -eq 0 ] && exit 1

. /usr/local/subr/download.subr
. /usr/local/subr/html.subr

for word in "$@"; do

	word="${word/./}"
	[[ "$word" =~ ^[a-z-]+/ ]] || word="present-tense/$word"

	curl_command "https://www.spanishconjugation.net/${word}/" \
		| extract_class '(verb-(translation|pronoun|entry verb-(normal|irregular|orto)))' '' \
		| awk 'BEGIN { i=1; printf("@"); }\
			{ if(i==1){ printf("%s\n",$0); i=0; } else { printf("%s ",$0); i++; } }'

done
