#!/bin/bash -eu

[ "$#" -eq 0 ] && exit 1

. /usr/local/subr/download.subr
. /usr/local/subr/html.subr

for word in "$@"; do

	word="${word/./}"

	curl_command "https://www.spanishconjugation.net/present-tense/${word}/" \
		| extract_class '(verb-entry verb-normal|verb-pronoun)' '' \
		| awk 'BEGIN { i=0 } { if(i==1){ printf("%s\n",$0); i=0; } else { printf("%s ",$0); i++; } }'

done
