#!/bin/sh -e
. /usr/subr/o
[ "$#" -eq 0 ] && exit 1
D='/usr/bbx'
[ -e $D ] || {
	pwrn "$D nexist, creating it"
	mkdir $D
}
O="$(busybox | awk '/Currently defined functions/,/EOF/' |
	tr ',' '\n' | sed '1d;/^$/d; s/[ 	]\+//g')"
for arg in "$@"; do
	if [ -e "$D/$arg" ]; then
		perrex "$arg already exists in $D" 1
	elif ! echo "$O" | grep -q "^$arg\$"; then
		perrex "$arg is not a valid bbx command" 2
	fi
done
for arg in "$@"; do
	ln -s ../bin/busybox $D/"$arg"
done
