#!/bin/sh -e
. /usr/subr/out
[ "$#" -eq 0 ] && exit 1
D='/usr/bbx'
[ -e $D ] || {
	pwrn "$D nexist, creating it"
	mkdir $D
}
A="$(busybox | awk '/Currently defined functions/,/EOF/' | sed 1d \
	| sed 's/[ 	]//g' | tr ',' '\n' | sed '/^$/d')"
for arg in "$@"; do
	if [ -e "$D/$arg" ]; then
		perrexit "$arg already exists in $D" 1
	elif ! echo "$A" | grep -q "^$arg\$"; then
		perrexit "$arg is not a valid bbx command" 2
	fi
done
for arg in "$@"; do
	ln -s ../bin/busybox $D/"$arg"
done
