#!/bin/sh -e
[ "$(id -u)" -ne 0 ] && exit 1
. /usr/subr/o
LF=/var/log/$PRGN
r() {
	printf "$1 --> "
	if $1 1>$LF 2>&1; then
		echo SUCC
	else
		perrex 'FAIL: ck '$LF 2
	fi
}
[ "$1" = --rinstgrub ] && r 'instgrub'
r 'mkinitcpio -P'
r 'grub-mkconfig -o /boot/grub/grub.cfg'
