#!/bin/sh -e
. /usr/subr/o
[ "$(id -u)" -ne 0 ] && exit 1
[ $# -ne 1 ] && exit 2
[ -e /encetc/wpa/"$1" ] ||
	perrex "/encetc/wpa/$1 nexist" 1
exec wpa_supplicant -i wlan0 \
	-c /encetc/wpa/"$1" 1>/var/log/wsd 2>&1
