#!/bin/sh -e
. /usr/subr/o
[ "$(id -u)" -ne 0 ] && exit 1
[ $# -ne 1 ] && exit 2
[ -e /encetc/wpa/"$1" ] || \
	perrex "/encetc/wpa/$1 nexist" 1
exec wpa_supplicant \
	-B -c /encetc/wpa/"$1" -i wlan0 \
	1>/var/log/wpad 2>&1
