#!/bin/sh -eu
[ "$(id -u)" -ne 0 ] && exit 1

. /usr/subr/out

readonly CONFD='/encetc/wpa_supplicant'
read -r -p 'SSID: ' SSID
readonly CONF="$CONFD/$SSID.conf"
PASS=''

[ -e "$CONF" ] && \
	perrexit "there is already a file named \
	$SSID.conf in $CONFD" 2

stty -echo
read -r -p 'PASS: ' PASS
echo
stty echo

cat <<EOF >"$CONF"
network={
        ssid="$SSID"
        key_mgmt=WPA-PSK
        psk="$PASS"
}
EOF
