#!/bin/bash -eu
SSID=''
PASS=''
read -p 'SSID: ' SSID
read -s -p 'PASS: ' PASS
install -m 0600 -o root -g root /dev/null /eetc/wpa/"$SSID"
cat << EOF > /eetc/wpa/"$SSID"
network={
	ssid="$SSID"
	scan_ssid=1
	key_mgmt=WPA-PSK
	psk="$PASS"
}
EOF
echo
