#!/bin/bash -e
read -rp 'SSID: ' SSID
read -srp 'PASS: ' PASS
install -m 0600 -o root -g root /dev/null /encetc/wpa/"$SSID"
cat <<EOF >/encetc/wpa/"$SSID"
network={
	ssid="$SSID"
	scan_ssid=1
	key_mgmt=WPA-PSK
	psk="$PASS"
}
EOF
echo
