#!/bin/sh -eu
[ "$#" -eq 0 ] && exit 1
. /usr/subr/out
for file in "$@"; do
	LINE="$(grep "^$(readlink -f "$file"):" /letc/swfl)"
	[ -z "$LINE" ] && continue
	diff "${LINE%%:*}" "$(echo "$LINE" | cut -d: -f2)" || continue
done
