#!/bin/sh -eu
[ "$#" -eq 0 ] && exit 1
. /usr/subr/out
for file in "$@"; do
	LINE="$(grep "^$(readlink -f "$file"):" /letc/swfl)"
	[ -z "$LINE" ] && continue
	TRGT="$(echo "$LINE" | cut -d: -f2)"
	[ ! -e "$TRGT" ] && continue
	SRC="${LINE%%:*}"
	if ! O="$(diff "$SRC" "$TRGT")"; then
		printf "$SRC\t$TRGT\n"
		echo "$O"
	fi
done
