#!/bin/sh -eu
[ "$#" -eq 0 ] && exit 1
VERB=0
[ "$1" = -v ] && {
	VERB=1
	shift 1
}
. /usr/subr/out
for file in "$@"; do
	if ! LINE="$(grep "^$(readlink -f "$file"):" /letc/swfl)"; then
		[ "$VERB" = 1 ] && \
			pwrn "$file nfound in /letc/swfl"
		continue
	fi
	TRGT="$(echo "$LINE" | cut -d: -f2)"
	[ ! -e "$TRGT" ] && continue
	SRC="${LINE%%:*}"
	if ! O="$(diff "$SRC" "$TRGT")"; then
		printf "$SRC\t$TRGT\n"
		echo "$O"
	fi
done
