#!/bin/sh -e
[ "$(id -u)" -ne 0 ] && exit 1
[ "$#" -eq 0 ] && exit 2
. /usr/subr/o
D=/mnt/strg/enc/bkup
[ ! -e $D ] && perrex "$D: nexist" 3
for d in "$@"; do
	[ -d "$d" ] || perrex "$d: ndir" 4
done
for dir in "$@"; do
	tar czf \
		$D/"$(readlink -f "$dir" |
		sed 's|/|_|g')@$(date +%Y-%m-%d@%T).tar.gz" \
		"$dir" >/dev/null
done
