#!/bin/sh -e
[ "$#" -eq 0 ] && exit 1
. /usr/subr/o
D=/mnt/strg/enc/bkup
if [ ! -e $D ]; then
	perrex "$D: nexist" 2
elif [ "$(stat -c '%a' "$D")" -ne 1777 ]; then
	perrex "$D: bad permission, not 1777" 3
fi
for d in "$@"; do
	[ -d "$d" ] || perrex "$d: ndir" 4
done
for dir in "$@"; do
	tar czf \
		$D/"$(readlink -f "$dir" |
		sed 's|/|_|g')@$(date +%Y-%m-%d@%T).tar.gz" \
		"$dir" >/dev/null
done
