#!/bin/bash -e
[ -z "$1" ] && exit 1
if [[ "$1" =~ ^-[a-zA-Z]+ ]]; then
	CMD="grep $1"
	shift 1
else
	CMD=grep
fi
P="$(sed \
	-e 's/a/[aá]/g' -e 's/e/[eé]/g' \
	-e 's/i/[ií]/g' -e 's/o/[oó]/g' \
	-e 's/u/[uú]/g' <<<"$1"\
)"
shift 1
$CMD "$P" "$@"
