#!/bin/sh -eu
. /usr/subr/out
for file in "$@"; do
	[ ! -f "$file" ] && exit 1
	grep -q -m1 "^$(readlink -f "$file"):" /letc/swfl || \
	       	perrexit "$file: nfound in /letc/swfl" 2
done
for file in "$@"; do
	FULLPATH="$(grep -m1 "^$(readlink -f "$file"):" /letc/swfl)"
	DEST="$(echo "$FULLPATH" | cut -d':' -f2)"
	PERM="${FULLPATH##*:}"
	file="${file%%:*}"
	echo "$file --> $DEST"
	if [ "$(stat -c '%u' "$file")" = 0 ]; then
		s install -m "$PERM" "$file" "$DEST"
	else
		install -m "$PERM" "$file" "$DEST"
	fi
done
