#!/bin/sh -eu
. /usr/subr/out
for f in "$@"; do
	[ ! -f "$f" ] && exit 1
	grep -q -m1 "^$(readlink -f "$f"):" /letc/swfl || perrexit "$f: nfound in /letc/swfl" 2
done
for f in "$@"; do
	FULLPATH="$(grep -m1 "^$(readlink -f "$f"):" /letc/swfl)"
	DEST="$(echo "$O" | cut -d':' -f2)"
	PERM="${O##*:}"
	f="${f%%:*}"
	echo "$f --> $DEST"
	if 
	install -m "$PERM" "$f" "$DEST"
done
