#!/bin/sh -e
[ "$(id -u)" -ne 0 ] && exit 1
. /usr/subr/o
ED=/boot/efi
if ! mount | \
  grep -q '^/dev/[^ ]\+ on '$ED; then
		perrex $ED' nmounted' 2
elif [ -n "$(ls -A /boot/efi)" ]; then
	T="$(mktemp -d)"
	mv $ED/* "$T"
fi
if ! grub-install --target=x86_64-efi \
  --efi-directory=$ED --bootloader-id=ARTIX; then
		perrex 'REINSTALLING GRUB FAILED' 3
elif ! efibootmgr | \
  grep -q '^Boot[0-9]\+\* ARTIX'; then
		perrex '"ARTIX" nfound in efibootmgr' 4
fi
[ -n "$T" ] && rm -r "$T"
