#!/bin/sh -eu
[ "$#" -gt 1 ] && exit 1
. /usr/subr/out
if [ "$PROGN" != 'pwroff' ] && [ "$PROGN" != 'rbt' ]; then
	exit 2
fi
O="$(who)"
echo "$O" | cut -d' ' -f1 | grep -Fvq "$USER" && {
	perr "somebody else is logged in, cannot pwroff:"
	echo "$O"
	exit 3
}
[ "$#" -eq 1 ] && case "$1" in
	-f|--force) exec loginctl "$PROGN";;
	*) exit 4 ;;
esac
pgrep Xorg 1>/dev/null && {
	perrex "an Xorg session is already running, cannot $PROGN" 5
}
case "$PROGN" in
	rbt) loginctl reboot ;;
	pwroff) loginctl poweroff ;;
esac
