#!/bin/sh -e
. /usr/subr/out
[ "$#" -eq 0 ] && exit 1
O="$(pacman -Qq)"
C="$(grep -o '^CacheDir.*$' /etc/pacman.conf | grep -o '/.*$')" || {
	C=/var/cache/pacman/pkg
}
for p in "$@"; do
	if [ ! -e "$p" ]; then
		if ! echo "$O" | grep -q "^$p$"; then
			perrexit "$p: pkg not found" 3
		fi
	p="$(find "$C" -name "$p-[0-9]*.pkg.tar.zst" | sort | tail -n1)"
	fi
	tar -O -xf "$p" .PKGINFO | grep ^optdepend | \
		sed 's/^optdepend = //' | while read -r od; do
			if echo "$O" | grep -q "^$(echo "$od" | cut -d':' -f1)$"; then
				printf "%s [I]\n" "$od"
			else
				echo "$od"
			fi
	done
done
