#!/bin/sh -e
. /usr/subr/out
[ "$#" -eq 0 ] && exit 1
O="$(pacman -Qq)"
C="$(sed -n '/^CacheDir/s/^[^/]\+//p' \
		/etc/pacman.conf)" || exit 2
for pkg in "$@"; do
	if [ ! -e "$pkg" ]; then
		if ! echo "$O" | grep -q "^$pkg$"; then
			perrex "$pkg: pkg nfound" 3
		fi
		pkg="$(find "$C" -name "$pkg-[0-9]*.pkg.tar.zst" | \
			sort | tail -n1)"
	fi
	tar -O -xf "$pkg" .PKGINFO | \
		sed -n '/^optdepend/s/^optdepend = //p' | \
		while read -r optdeps; do
			if echo "$O" | grep -q "^${optdeps%%:*}$"; then
				printf "%s [I]\n" "$optdeps"
			else
				echo "$optdeps"
			fi
		done
done
