#!/bin/sh -e
e=0
while true; do
	O="$(iw wlan0 scan 2>&1)"
	if [ $e -eq 5 ]; then
		echo "$O"
		break
	elif echo "$O" | grep -qFi \
	  'command failed: device or resource busy' ||
	  [ -z "$O" ]; then
			e=$((E+1))
			sleep 2s
	else
		echo "$O" | sed -n '/SSID: ./s/^[ \t]\+SSID: //p'
		break
	fi
done
