#!/bin/sh -eu
[ "$#" -eq 0 ] && exit 1
. /usr/subr/o
for f in "$@"; do
	[ ! -f "$f" ] && {
		perrex "\"$f\" is nfile" 2
	}
done
for f in "$@"; do
	n=1
	while true; do
		if [ $n -ge 1000 ]; then
			perrex "out of numbers" 3
		elif [ -e "${f}.orig.${n}" ]; then
				n=$((n+1))
				continue
		fi
		break
	done
	cp "$f" "${f}.orig.${n}"
done
