#!/bin/sh -eu
[ "$#" -eq 0 ] && exit 1
. /usr/subr/out
for file in "$@"; do
	[ ! -f "$file" ] && {
		perr "\"$file\" is not a file"
		exit 2
	}
done
for file in "$@"; do
	N=1
	while true; do
		[ $N -ge 1000 ] && {
			perr "out of numbers"
			exit 3
		}
		[ -e "${file}.orig.${N}" ] && N=$((N+1)) && continue
		break
	done
	cp "$file" "${file}.orig.${N}"
done
