#!/bin/sh -eu
[ "$(id -u)" -ne 0 ] && exit 1
pgrep -f wpa_supplicant 1>/dev/null && \
	killall wpa_supplicant
while true; do
	lsssids | while read -r ssid; do
		if [ -e /encetc/wpa/"$ssid" ]; then
			connssid "$ssid"
			i=0
			sleep 10s
			while [ $i -lt 10 ]; do
				if lsssids | grep -q "^${ssid}$"; then
					i=0
				else
					i=$((i+1))
				fi
				sleep 10s
			done
			killall wpa_supplicant
			break
		fi
	done
done
