#!/bin/sh
if [ "$(id -u)" -eq 0 ]; then
	echo 'ERR: startx not allowed as root' 1>&2
	exit 1
elif pgrep -u "$USER" Xorg 1>/dev/null; then
	echo 'ERR: an Xorg session is already running' 1>&2
	exit 2
fi
exec /bin/startx "$@"
