#!/bin/sh -eu
. /usr/subr/out
for file in "$@"; do
	[ ! -f "$file" ] && exit 1
	grep -q -m1 "^$(readlink -f "$file"):" /letc/swfl || \
	       	perrex "$file: nfound in /letc/swfl" 2
done
for file in "$@"; do
	FULP="$(grep -m1 "^$(readlink -f "$file"):" /letc/swfl)"
	DEST="$(echo "$FULP" | cut -d':' -f2)"
	PERM="${FULP##*:}"
	file="${file%%:*}"
	echo "$file --> $DEST"
	if [ "$(stat -c '%u' "$DEST")" = 0 ] || \
		[ "$(stat -c '%u' "$(dirname "$DEST")")" = 0 ]; then
			s install -m "$PERM" "$file" "$DEST"
	else
		install -m "$PERM" "$file" "$DEST"
	fi
done
