#!/bin/sh -eu
. /usr/subr/o
if [ -e "$HOME"/.swfl ]; then
	F=/letc/swfl\ "$HOME"/.swfl
else
	F=/letc/swfl
fi
sed 's/:[0-9]\+$//; s/:/ /g' $F |
	while read -r line; do
		SRC="${line%% *}"
		TGT="${line##* }"
		if [ ! -e "$SRC" ]; then
			pwrn "$SRC: nexist"
			continue
		elif [ ! -e "$TGT" ]; then
			pwrn "$TGT: nexist"
			continue
		fi
		diff $line || echo "@ $line"
	done
