#!/bin/sh -eu

. /usr/subr/o

if [ "$#" -lt 2 ]; then
	echo "USAGE: $PRGN @src @tgt #perm"
	exit 1
elif [ -L "$1" ] || [ -L "$2" ]; then
	perrex 'src or file cant be link' 2
elif [ "$(id -u)" -ne 0 ]; then
	exit 3
elif [ ! -f "$1" ]; then
	perrex 'src must be a file' 4
fi

if [ -d "$2" ]; then
	TGT="${2%/}/${1##*/}"
else
	TGT="$2"
fi

if [ "$#" -lt 3 ]; then
	if [ -d "$2" ]; then
		PERM=0644
	elif [ -f "$2" ]; then
		PERM="$(stat -c "%a" "$2")"
	fi
else
	PERM="$3"
fi

L="$(readlink -f "$1"):$TGT:$PERM"
grep -q "^$L\$" /letc/swfl &&
	perrex "$1: line already added" 5
grep -q "^${L%%:*}:" /letc/swfl &&
	perrex "$1: src file already added" 6
exec echo "$L" >>/letc/swfl
