#!/bin/sh -e
. /usr/subr/out
if [ "$#" -lt 2 ]; then
	echo "USAGE: ${0##*/} @src @trgt #perm"
	exit 1
elif [ "$(id -u)" -ne 0 ]; then
	exit 2
fi
if [ -z "$3" ]; then
	if [ ! -e "$2" ];then
		PERM=0644
	else
		PERM="$(stat -c "%a" "$2")"
	fi
else
	PERM="$3"
fi
L="$(readlink -f "$1"):$(readlink -f "$2"):$PERM"
grep -q "^$L\$" /letc/swfl && perrexit "already added" 2
exec echo "$L" >> /letc/swfl
