#!/bin/sh -e
. /usr/subr/out
if [ "$#" -lt 2 ]; then
	echo "USAGE: ${0##*/} @src @tgt #perm"
	exit 1
elif [ "$(id -u)" -ne 0 ]; then
	exit 2
elif [ ! -f "$1" ]; then
	perrex 'src must be a file' 3
elif [ ! -d "$2" ]; then
	perrex 'tgt must be directory' 4
fi
if [ -z "$3" ]; then
	if [ ! -e "$2" ]; then
		PERM=0644
	else
		PERM="$(stat -c "%a" "$2")"
	fi
else
	PERM="$3"
fi
L="$(readlink -f "$1"):$(readlink -f "$2")/${1##*/}:$PERM"
grep -q "^$L\$" /letc/swfl && perrex "$1: line already added" 5
grep -q "^${L%%:*}:" /letc/swfl && perrex "$1: src file already added" 6
exec echo "$L" >>/letc/swfl
