#!/bin/sh -e
if [ "$#" -lt 2 ]; then
	echo "USAGE: ${0##*/} [src file] [trgt] [perm]"
	exit 1
elif [ "$(id -u)" -ne 0 ]; then
	exit 2
fi
if [ -z "$3" ]; then
	PERM=0644
else
	PERM="$3"
fi
exec echo "$(readlink -f "$1"):$(readlink -f "$2"):$PERM" >> /letc/swfl
