#!/bin/sh -eu
. /usr/subr/o
F=/letc/swfl
for file in "$@"; do
	[ ! -f "$file" ] && exit 1
	grep -q -m1 "^$(readlink -f "$file"):" $F ||
		perrex "$file: nfound in $F" 2
done
for file in "$@"; do
	FULP="$(grep -m1 "^$(readlink -f "$file"):" $F)"
	DEST="$(echo "$FULP" | cut -d':' -f2)"
	PERM="${FULP##*:}"
	file="${file%%:*}"
	install -m "$PERM" "$file" "$DEST"
done
