#!/bin/sh -eu

. /usr/local/subr/output.subr

[ "$(id -u)" -ne 0 ] && {
	print_error 'you must be root'
	exit 1
}

LOG_FILE="/var/log/tor/$PROGRAM_NAME.log"
URL='https://html.duckduckgo.com'
CURL_OPTIONS='--silent -L'
SOCKS5_ADDRESS=''
PID=''
TMP_FILE=''
TOR_DAEMONS=''

write_log() { echo "$(date '+%Y-%m(%b)-%d %H:%M'): $1" >> "$LOG_FILE" ; }

cd /tmp

TMP_FILE="${LOG_FILE##*/}"
[ ! -e "$TMP_FILE" ] && mkdir -p "$TMP_FILE"
printf '' > "$LOG_FILE"

while true; do

	sleep 30s

	TOR_DAEMONS="$(ss -alpn | grep -F '"tor"' | sed 's/ \+/ /g')"

	[ -z "$TOR_DAEMONS" ] && {
		write_log '[WARNING]: could not find any tor daemon'
		continue
	}

	echo "$TOR_DAEMONS" | while read -r tor_info_line; do
		SOCKS5_ADDRESS="$(echo "$tor_info_line" | cut -d' ' -f5)"
		PID="$(echo "$tor_info_line" | grep -o 'pid=[0-9]\+')"

		if ! pgrep -f "curl $CURL_OPTIONS --socks5 $SOCKS5_ADDRESS $URL" 1>/dev/null; then

			if env -i PATH='/bin:/sbin' su - nobody -s /bin/sh -c "exec curl $CURL_OPTIONS --socks5 $SOCKS5_ADDRESS $URL 0<&- 1>/dev/null 2>&1"; then
				write_log "[CURL SUCCESS]: $SOCKS5_ADDRESS,$PID"
			else
				write_log "[CURL FAIL]: $SOCKS5_ADDRESS,$PID"
			fi

		fi &
	done

	if [ "$(wc -l "$LOG_FILE" | cut -d' ' -f1)" -ge 100 ]; then

		while pgrep -f "curl $CURL_OPTIONS --socks5 [0-9.]\+:[0-9]\+ $URL" 1>/dev/null; do
			sleep 1s
		done

		TMP_FILE="$(mktemp)"
		grep -F '[CURL SUCCESS]' "$LOG_FILE" | tail -n20 > "$TMP_FILE"
		cat "$TMP_FILE" > "$LOG_FILE"
		rm "$TMP_FILE"

	fi

done
