#!/bin/sh

set -eu

. /etc/sh.subr

[ "$(id -u)" -ne 0 ] && print_error 'you must be root' && exit 1

LOG_FILE="/var/log/$PROGRAM_NAME.log"
URL='https://html.duckduckgo.com'
SOCKS5_ADDRESS=''
PID=''
TMP_FILE=''

write_log() { echo "$(date '+%Y-%m(%b)-%d %H:%M'): $1" >> "$LOG_FILE" ; }

cd /tmp

printf '' > "$LOG_FILE"

while true; do

	sleep 30s
	ps -A -o cmd | cut -d' ' -f1 | grep -q '\btor\b' || {
		write_log "[WARNING]: could not find any tor daemon"
		continue
	}

	ss -alpn | grep -F '"tor"' | sed 's/ \+/ /g' | while read -r tor_info_line; do
		SOCKS5_ADDRESS="$(echo "$tor_info_line" | cut -d' ' -f5)"
		PID="$(echo "$tor_info_line" | grep -o 'pid=[0-9]\+')"

		if env -i PATH='/bin:/sbin' su - nobody -s /bin/sh -c "exec curl --silent -L --socks5 $SOCKS5_ADDRESS $URL 0<&- 2>&1 1>/dev/null"; then
			write_log "[CURL SUCCESS]: $SOCKS5_ADDRESS,$PID"
		else
			write_log "[CURL FAIL]: $SOCKS5_ADDRESS,$PID"
		fi &
	done

	while ps -A -o cmd | grep "curl --silent -L --socks5 [0-9.]\+:[0-9]\+ $URL" 1>/dev/null; do
		sleep 1s
	done

	if [ "$(wc -l "$LOG_FILE" | cut -d' ' -f1)" -ge 50 ]; then
		TMP_FILE="$(mktemp)"
		grep -F '[CURL SUCCESS]' "$LOG_FILE" | tail -n10 > "$TMP_FILE"
		cat "$TMP_FILE" > "$LOG_FILE"
		rm "$TMP_FILE"
	fi

done
