#!/bin/sh -e
for f in /var/log/tor/tor*.log; do
	L="$(basename "$f" '.log')"
	pgrep -f "$L" 1>/dev/null || W='(pid not found)'
	printf '%s: %s %s\n' "$L" "$(grep -o '[0-9]\+%' "$f" | tail -n1)" "$W"
done
