#!/bin/sh -e
for file in /var/log/tor/tor*.log; do
	LOGF="$(basename "$file" '.log')"
	pgrep -f "$LOGF" 1>/dev/null || WARN='(pid not found)'
	printf '%s: %s %s\n' "$LOGF" "$(grep -o '[0-9]\+%' "$file" | tail -n1)" "$WARN"
done
