#!/bin/sh -eu

. /usr/local/subr/out.subr

readonly DEP_PROG='trcd'
readonly LOGF="/var/log/tor/$DEP_PROG.log"
PID=''
OUT=''
NUM_OF_LINES=0

if ! pgrep -f "$DEP_PROG" 1>/dev/null; then
	pwarn "this program depends on the program $DEP_PROG, however, it is not running, this might cause some problems"
fi

[ ! -e "$LOGF" ] && perr "$LOGF does not exist" && exit 1
[ ! -s "$LOGF" ] && perr "$LOGF is empty" && exit 1

OUT="$(grep -F '[CURL SUCCESS]' "$LOGF")" || {
	perr "no suitable tor address that has a successful connection to the tor network was found in logfile $LOGF"
	exit 1
}

NUM_OF_LINES="$(echo "$OUT" | wc -l | cut -d' ' -f1)"
i=1
echo "$OUT" | tac | while read -r line; do
	PID="$(echo "$line" | grep -o 'pid=[0-9]\+' | cut -d'=' -f2)"
	if ! ps -p "$PID" 1>/dev/null; then
		[ "$i" -eq "$NUM_OF_LINES" ] && {
			perr "no suitable tor address associated with a running process was found"
			exit 1
		}
		i="$((i+1))"
		continue
	fi

	echo "$line" | grep -oE '([0-9]{1,3}.){3}[0-9]{1,3}:[0-9]+'
	break
done
