#!/bin/sh -eu

. /usr/local/subr/io.subr

DEPENDENT_PROGRAM='keep-tor-connections-alive'
LOG_FILE="/var/log/tor/$DEPENDENT_PROGRAM.log"
PID=''
GREP_OUTPUT=''
NUM_OF_LINES=0

if ! pgrep -f "$DEPENDENT_PROGRAM" 1>/dev/null; then
	print_warning "this program depends on the program $DEPENDENT_PROGRAM, however, it is not running, this might cause some problems"
fi

[ ! -e "$LOG_FILE" ] && print_error "$LOG_FILE does not exist" && exit 1
[ ! -s "$LOG_FILE" ] && print_error "$LOG_FILE is empty" && exit 1

GREP_OUTPUT="$(grep -F '[CURL SUCCESS]' "$LOG_FILE")" || {
	print_error "no suitable tor address that has a successful connection to the tor network was found in logfile $LOG_FILE"
	exit 1
}

NUM_OF_LINES="$(echo "$GREP_OUTPUT" | wc -l | cut -d' ' -f1)"
i=1
echo "$GREP_OUTPUT" | tac | while read -r line; do
	PID="$(echo "$line" | grep -o 'pid=[0-9]\+' | cut -d'=' -f2)"
	if ! ps -p "$PID" 1>/dev/null; then
		[ "$i" -eq "$NUM_OF_LINES" ] && {
			print_error "no suitable tor address associated with a running process was found"
			exit 1
		}
		i="$((i+1))"
		continue
	fi

	echo "$line" | grep -oE '([0-9]{1,3}.){3}[0-9]{1,3}:[0-9]+'
	break
done
