#!/bin/sh -eu

. /usr/subr/out
readonly LOGF="/var/log/tor/$PROGN.log"
readonly CURL_ARGS='--silent -L https://html.duckduckgo.com'
SOCKS5_ADDR=''
PID=''
TMP=''
TOR_DAEMONS=''
log() { echo "$1" >> "$LOGF" ; }

if [ "$(id -u)" -ne 0 ]; then
	exit 1
elif ! command -v nobody-curl 1>/dev/null; then
	exit 2
fi

TMP="${LOGF%/*}"
[ ! -e "$TMP" ] && mkdir -p "$TMP"
printf '' > "$LOGF"
cd /

while true; do
	sleep 30s

	TOR_DAEMONS="$(ss -alpn | grep -F '"tor"' | sed 's/ \+/ /g')"
	[ -z "$TOR_DAEMONS" ] && {
		log '[WARNING]: could not find any tor daemons'
		continue
	}

	echo "$TOR_DAEMONS" | while read -r tor_info_line; do
		SOCKS5_ADDR="$(echo "$tor_info_line" | cut -d' ' -f5)"
		PID="$(echo "$tor_info_line" | grep -o 'pid=[0-9]\+')"
		if ! pgrep -f "nobody-curl --socks5 $SOCKS5_ADDR $CURL_ARGS" 1>/dev/null; then
			if nobody-curl --socks5 "$SOCKS5_ADDR" $CURL_ARGS 0<&- 1>/dev/null 2>&1; then
				log "[CURL SUCC]: $SOCKS5_ADDR,$PID"
			else
				log "[CURL FAIL]: $SOCKS5_ADDR,$PID"
			fi
		fi &
	done

	if [ "$(wc -l "$LOGF" | cut -d' ' -f1)" -ge 100 ]; then
		while pgrep -f "nobody-curl --socks5 [0-9.]\+:[0-9]\+ $CURL_ARGS" 1>/dev/null; do
			sleep 1s
		done
		TMP="$(mktemp)"
		grep -F '[CURL SUCC]' "$LOGF" | tail -n20 > "$TMP"
		cat "$TMP" > "$LOGF"
		rm "$TMP"
	fi
done
