#!/bin/sh -eu

. /usr/local/subr/out.subr

LOGF="/var/log/tor/$PROG_NAME.log"
URL='https://html.duckduckgo.com'
CURL_OPTIONS='--silent -L'
SOCKS5_ADDR=''
PID=''
TMP=''
TOR_DAEMONS=''

log() { echo "$(date '+%Y-%m(%b)-%d %H:%M'): $1" >> "$LOGF" ; }

[ "$(id -u)" -ne 0 ] && {
	perr 'you must be root'
	exit 1
}
command -v nobody-curl 1>/dev/null || {
	perr 'nobody-curl: command does not exist'
	exit 2
}

TMP="${LOGF%/*}"
[ ! -e "$TMP" ] && mkdir -p "$TMP"
printf '' > "$LOGF"
cd /

while true; do
	sleep 30s
	TOR_DAEMONS="$(ss -alpn | grep -F '"tor"' | sed 's/ \+/ /g')"

	[ -z "$TOR_DAEMONS" ] && {
		log '[WARNING]: could not find any tor daemon'
		continue
	}

	echo "$TOR_DAEMONS" | while read -r tor_info_line; do
		SOCKS5_ADDR="$(echo "$tor_info_line" | cut -d' ' -f5)"
		PID="$(echo "$tor_info_line" | grep -o 'pid=[0-9]\+')"
		if ! pgrep -f "nobody-curl $CURL_OPTIONS --socks5 $SOCKS5_ADDR $URL" 1>/dev/null; then
			if nobody-curl $CURL_OPTIONS --socks5 $SOCKS5_ADDR $URL 0<&- 1>/dev/null 2>&1; then
				log "[CURL SUCCESS]: $SOCKS5_ADDR,$PID"
			else
				log "[CURL FAIL]: $SOCKS5_ADDR,$PID"
			fi
		fi &
	done

	if [ "$(wc -l "$LOGF" | cut -d' ' -f1)" -ge 100 ]; then
		while pgrep -f "nobody-curl $CURL_OPTIONS --socks5 [0-9.]\+:[0-9]\+ $URL" 1>/dev/null; do
			sleep 1s
		done
		TMP="$(mktemp)"
		grep -F '[CURL SUCCESS]' "$LOGF" | tail -n20 > "$TMP"
		cat "$TMP" > "$LOGF"
		rm "$TMP"
	fi
done
