[[ ! "$-" =~ i ]] && return

set -o vi

HISTCONTROL='ignoredups'
HISTFILE="$HOME/.bash_history"
HISTFILESIZE=999999
HISTSIZE=99999
PS1='$ $?: '
EDITOR=vim

bind "\C-l":clear-screen
bind "\C-f":reverse-search-history
bind -r "\C-s"
bind -r "\C-p"
bind "\C-s":vi-movement-mode
bind "\C-x":vi-movement-mode
bind "\C-a":beginning-of-line
bind "\C-e":end-of-line
bind '"\C-r":". $HOME/.bashrc\n"'
bind '"\C-n":"nohup st 1>/dev/null 2>&1 &\n"'

shopt -s autocd
shopt -s checkwinsize
shopt -s cmdhist
shopt -s histappend

stty stop ''

. /usr/local/subr/download.subr
. /etc/aliasrc
. "$HOME"/.bash_functions

alias vt="vim $HOME/.tasks"
alias vct="vim $HOME/.current_tasks"
alias vtmp='vim "$(mktemp)"'
alias do-diffmgr='find ~/Software/mgit/lancia-utils/* -type f | xargs diffmgr'
alias ytdl-mp3-proxy='youtube-dl --proxy "socks5://$(tpsel)" --extract-audio --audio-format mp3 --audio-quality 0'
