runtime! archlinux.vim

set nocompatible
set ttymouse=""
set mouse=""
set shortmess=aI
set formatoptions=crql

map <F1> <NOP>
map <Return> <NOP>
map <C-n> <NOP>
map <C-z> <NOP>
map <C-n> <NOP>
map <C-m> <NOP>
map <C-x> <NOP>

nnoremap <C-s> :w<nl>
nnoremap <C-x> :q<nl>
nnoremap <C-z> <undo>
nnoremap <C-c> :.w !xclip -selection clipboard<nl><nl>
nnoremap <C-n> :bn<nl>
nnoremap <C-m> :bp<nl>
nnoremap <F1> :%w !clipboard<nl><nl>
nnoremap <F2> :!ccw %<nl><nl>

inoremap <C-x> <Esc>
inoremap <C-s> <Esc>
inoremap <C-z> <Esc><undo><insert>
inoremap <C-c> <Esc>:.w !xclip -selection clipboard<nl><insert>

vnoremap <C-c> y<nl>:call system('xclip -selection clipboard', @0)<nl>
vnoremap <C-x> <Esc>

autocmd BufNewFile,BufRead *.subr set syntax=sh
autocmd BufNewFile,BufRead *i3* set syntax=i3config
autocmd BufNewFile,BufRead *bash* set syntax=bash
