runtime! archlinux.vim

set nocompatible
set ttymouse=""
set mouse=""
set shortmess=aI
set formatoptions=crql

autocmd BufNewFile,BufRead *.subr set syntax=sh
autocmd BufNewFile,BufRead *i3* set syntax=i3config
autocmd BufNewFile,BufRead *bash* set syntax=bash
autocmd BufNewFile,BufRead *vimrc* set syntax=vim

source /etc/vimrc.map
