#!/bin/sh

set -eu

[ "$#" -ne 1 ] && echo 'Error: need only one argument' 1>&2 && exit 1

FILTER_PATTERN='^"contextE(n|s)"|^"translation"|^"textE(n|s)"|"(feminine|masculine|masculine or feminine) noun"'

curl --silent -L --socks5 "$(tpsel)" --user-agent "$USERAGENT" "https://www.spanishdict.com/translate/$1" | grep -o '"[^"]\+":"[^"]\+"' | \

	grep -E "$FILTER_PATTERN" | sed -e 's/"//g' -e 's/:/: /g' 
