#!/bin/sh

set -eu

COMMENT_IDENTIFIER='#BRIDGE,'

if [ "$1" = 'enable' ]; then

	sed -i "s/^$COMMENT_IDENTIFIER//" /etc/tor/torrc

elif [ "$1" = 'disable' ]; then

	sed -i "s/^Bridge obfs4/${COMMENT_IDENTIFIER}Bridge obfs4/;\
		s/^UseBridges/${COMMENT_IDENTIFIER}UseBridges/;\
		s/^ClientTransportPlugin/${COMMENT_IDENTIFIER}ClientTransportPlugin/" /etc/tor/torrc

fi
