#!/bin/sh

set -eu

LOG_FILE="/var/log/tor-$1.log"

[ ! -e "$LOG_FILE" ] && echo "Error: file $LOG_FILE non existent" && exit 1

PATTERN='Bootstrapped [0-9]\?[0-9]\?[0-9]%'

grep "$PATTERN" "$LOG_FILE" | tail

tail -f "$LOG_FILE" | grep "$PATTERN"
