#!/bin/sh

set -eu

DEPENDENT_PROGRAM='keep-tor-alive'

LOG_FILE="/var/log/$DEPENDENT_PROGRAM.log"

PROGRAM_NAME="$(basename "$0")"

if ! pgrep -f "$DEPENDENT_PROGRAM" 1>/dev/null; then

	echo "$PROGRAM_NAME: the script depends on the program $DEPENDENT_PROGRAM however it is not running" 1>&2

	exit 1

fi

[ ! -s "$LOG_FILE" ] && echo "$PROGRAM_NAME: $LOG_FILE empty" 1>&2 && exit 1

GREP_OUTPUT="$(grep -F 'Succeeded' "$LOG_FILE")" || {

	echo '$PROGRAM_NAME: no suitable tor address with a successful connection found' 1>&2

	exit 1

}

echo "$GREP_OUTPUT" | tail -n1 | grep -oE '([0-9]{1,3}.){3}[0-9]{1,3}:[0-9]+'
