#!/bin/sh -e
. /usr/subr/Xout
CMDL="$(dmenu < /dev/null)"
[ -z "$CMDL" ] && exit 0
COM="${CMDL%% *}"
command -v "$COM" 1>/dev/null 2>&1 || {
	perr "command \"$COM\" not found"
	exit 1
}
[ "$1" = '-s' ] && eval exec "$CMDL"
O="$(eval "$CMDL" 2>&1)" || {
	print "$(printf '"%s",exit(%i): %s\n' "$CMDL" "$?" "$O")"
	exit 2
}
print "$O"
