#!/bin/bash -eu
BRWSR="${1%%* }"
case "$(printf 'ddg\ngoogle\nstackoverflow\nwikipedia\narchwiki\nurl' | dmenu -p $BRWSR)" in
	ddg) URL='https://lite.duckduckgo.com/lite/?q=' ;;
	archwiki) URL='https://wiki.archlinux.org/index.php?search=' ;;
	wikipedia) URL='https://en.wikipedia.org/wiki/' ;;
	google) URL='https://google.com/search?hl=en&q=' ;;
	stackoverflow) URL='https://stackoverflow.com/search?q=' ;;
	url) URL='' ;;
	*) exit 1;;
esac
SRCH="$(dmenu -p "$BRWSR|$SITE" </dev/null)"
if [ $BRWSR = lynx ]; then
	if [[ "$(cat /proc/$PPID/comm)" =~ ^bash$|^sh$ ]]; then
		exec lynx "$URL$SRCH"
	else
		exec st lynx "$URL$SRCH"
	fi
else
	exec $1 "$URL$SRCH"
fi
