#!/bin/bash -eu
BRWSR=${1%%* }
DIR=~/dl/brwsr/$BRWSR; [ ! -e $DIR ] && mkdir $DIR
if [ "$#" -eq 2 ]; then
	SITE=$2
else
	SITE=$(printf 'ddg\nggl\nstackoverflow\nwikipedia\narchwiki\nurl' | dmenu -p $BRWSR)
fi
case $SITE in
	ddg) FPL='https://lite.duckduckgo.com/lite/?q=' ;;
	archwiki) FPL='https://wiki.archlinux.org/index.php?search=' ;;
	wikipedia) FPL='https://en.wikipedia.org/wiki/' ;;
	ggl) FPL='https://google.com/search?hl=en&q=' ;;
	stackoverflow) FPL='https://stackoverflow.com/search?q=' ;;
	url) FPL='' ;;
	*) exit 1;;
esac
IS="$(dmenu -p "$BRWSR|$SITE" </dev/null | tr \  +)"
[ -z "$IS" ] && exit 0
URL="$FPL$IS"
cd $DIR
if [ $BRWSR = lynx ]; then
	if [[ "$(cat /proc/$PPID/comm)" =~ ^bash$|^sh$ ]]; then
		exec lynx "$URL"
	else
		exec st lynx "$URL"
	fi
else
	exec $1 "$URL"
fi
