#!/bin/bash -eu
. /usr/subr/Xo
I="$(dmenu -p "$PRGN:" </dev/null)" || exit $?
O="$(hunspell <<<"$I" | sed -r '/^$|^Hunspell [0-9.]+/d')"
if [[ "$O" =~ ^# ]]; then
	perrex "\"$I\" nfound in dict" 1
elif [[ "$O" =~ ^\*$ ]]; then
	pmsg 'Word correct'
	clipb <<<"$I"
elif [[ "$O" =~ \+\ [[:alnum:]]+ ]]; then
	O="${O#+ }"
	printf '%s\n%s' "$O" "$I" | \
		dmenu -p "$I: plural of \"$O\"" | \
		clipb <<<"$I"
else
	echo "${O##*: }" | tr ',' '\n' | \
		dmenu | clipb
fi
