#!/bin/bash -eu
if [ "$#" -eq 0 ]; then
	F="$(printf 'ddg\ngoogle\nwikipedia\narchwiki' | dmenu -p lynx)"
else
	F="$1"
fi
case "$F" in
	ddg) U='https://lite.duckduckgo.com/lite/?q=' ;;
	archwiki) U='https://wiki.archlinux.org/index.php?search=' ;;
	wikipedia) U='https://en.wikipedia.org/wiki/' ;;
	google) U='https://google.com/search?q=' ;;
	*) exit 1;;
esac
I="$(dmenu -p "lynx|$F" </dev/null)"
if [[ "$(cat /proc/$PPID/comm)" =~ ^bash$|^sh$ ]]; then
	exec lynx -nocolor -vikeys "$U$I"
else
	exec st lynx -nocolor -vikeys "$U$I"
fi
