#!/bin/sh -eu
[ "$#" -ne 1 ] && exit 1
DIR="$HOME/Screenshot"
DATE="$(date +%D-%T | sed 's|/|_|g')"
[ ! -e "$DIR/$DATE" ] && mkdir -p "$DIR/$DATE"
N=0
for i in $(seq 1 1000); do
	[ -e "$DIR/$DATE/$i.png" ] && continue
	N="$i"
	break
done
F="$DIR/$DATE/$N.png"
case "$1" in
	full) import -window root "$F" ;;
	window) import -window "$(xwininfo | grep -F 'wininfo: Window id:' | cut -d' ' -f4)" "$F" ;;
	region) import "$F" ;;
	*) exit 2 ;;
esac
xclip -selection clipboard -t image/png -i "$F"
