#!/bin/sh -eu
[ "$#" -ne 1 ] && exit 1
D="$HOME/scsht"
DT="$(date +%Y-%m-%d)"
[ ! -e "$D/$DT" ] && mkdir -p "$D/$DT"
N=0
for i in $(seq 1 1000); do
	[ -e "$D/$DT/$i.png" ] && continue
	N="$i"
	break
done
F="$D/$DT/$N.png"
case "$1" in
	f) import -window root "$F" ;;
	w) import -window "$(xwininfo |\
		grep -F 'wininfo: Window id:' |\
		cut -d' ' -f4)" "$F" 
	;;
	r) import "$F" ;;
	*) exit 2 ;;
esac
xclip -sel clip -t image/png -i "$F"
