#!/bin/sh

set -e

PROXY="$(tpsel)" || {

	notify-send 'Selecting proxy failed, not launching chromium...'
	exit 1

}

case "$1" in

	primary-tor) exec chromium --proxy-server="socks5://$PROXY" ;;

	secondary-tor)

		DIR="$HOME/.config/chromium.tor"

		[ ! -e "$DIR" ] && exit 1

		exec chromium --proxy-server="socks5://$PROXY" --user-data-dir="$DIR"

	;;

	*) exit 1 ;;

esac
