#!/bin/bash -eu

. /usr/local/subr/X.out.subr

INPUT="$(dmenu -p "$PROGN:" < /dev/null)" || exit $?
OUT="$(hunspell <<< "$INPUT" | sed -r '/^$|^Hunspell [0-9.]+/d')"

if [[ "$OUT" =~ ^# ]]; then
	perr "Word \"$INPUT\" not found in dictionary"
	exit 1
elif [[ "$OUT" =~ ^\*$ ]]; then
	pmsg 'Word correct'
	echo "$INPUT" | tr -d '\n' | xclip -selection clipboard
elif [[ "$OUT" =~ \+\ [[:alnum:]]+ ]]; then
	OUT="${OUT#+ }"
	printf '%s\n%s' "$OUT" "$INPUT" | dmenu -p "\"$INPUT\": plural form of \"$OUT\"" | tr -d '\n' | xclip -selection clipboard
else
	cut -d':' -f2 <<< "$OUT" | tr -d ' ' | tr ',' '\n' | dmenu | tr -d '\n' | xclip -selection clipboard
fi
