#!/bin/bash -eu

. /usr/local/subr/X.out.subr

INPUT="$(dmenu -p 'Enter your word:' < /dev/null)" || exit $?
SPELL_OUTPUT="$(hunspell <<< "$INPUT" | sed -e '/^$/d' -e '/^Hunspell/d')"

if [[ "$SPELL_OUTPUT" =~ ^# ]]; then
	print_error "Word \"$INPUT\" not found in dictionary"
	exit 1
elif [[ "$SPELL_OUTPUT" =~ ^\*$ ]]; then
	print_msg 'Word correct'
	echo "$INPUT" | tr -d '\n' | xclip -selection clipboard
elif [[ "$SPELL_OUTPUT" =~ \+\ [[:alnum:]]+ ]]; then
	SINGULAR_WORD="${SPELL_OUTPUT#+ }"
	printf '%s\n%s' "$SINGULAR_WORD" "$INPUT" | dmenu -p "\"$INPUT\" is the plural form of \"$SINGULAR_WORD\"" | tr -d '\n' | xclip -selection clipboard
else
	cut -d':' -f2 <<< "$SPELL_OUTPUT" | tr -d ' ' | tr ',' '\n' | dmenu | tr -d '\n' | xclip -selection clipboard
fi
