#!/bin/sh -e

. /usr/local/subr/X.out.subr

CMDLINE="$(dmenu < /dev/null)"
[ -z "$CMDLINE" ] && exit 0

COMMAND="${CMDLINE%% *}"
command -v "$COMMAND" 1>/dev/null 2>&1 || {
	perr "command \"$COMMAND\" not found"
	exit 1
}

[ "$1" = '-s' ] && eval exec "$CMDLINE"

OUTPUT="$(eval "$CMDLINE" 2>&1)" || {
	print "$(printf '"%s",exit(%i): %s\n' "$CMDLINE" "$?" "$OUTPUT")"
	exit 2
}
print "$OUTPUT"
