#!/bin/sh -eu

[ "$#" -ne 1 ] && exit 1

SCREENSHOT_DIR="$HOME/Screenshot"
DATE="$(show-date)"
[ ! -e "$SCREENSHOT_DIR/$DATE" ] && mkdir -p "$SCREENSHOT_DIR/$DATE"

NUM=0
for i in $(seq 1 1000); do
	[ -e "$SCREENSHOT_DIR/$DATE/$i.png" ] && continue
	NUM="$i"
	break
done

FILE="$SCREENSHOT_DIR/$DATE/$NUM.png"
case "$1" in
	full) import -window root "$FILE" ;;
	window) import -window "$(xwininfo | grep -F 'wininfo: Window id:' | cut -d' ' -f4)" "$FILE" ;;
	region) import "$FILE" ;;
	*) exit 2 ;;
esac

xclip -selection clipboard -t image/png -i "$FILE"
