#!/bin/sh
case $1 in
	start)
		start-stop-daemon \
			--start --background \
			--exec /sbin/dhclient
			-- -4 -i wlan0
	;;
	stop)
		killall dhclient
	;;
	restart)
		$0 stop
		$0 start
	;;
	*) exit 1 ;;
esac
