#!/bin/sh -eu
. /etc/genv
. /usr/subr/o
case $1 in
	start)
		O="$(ifconfig)"
		echo "$O" | grep -q '^lo:' ||
			ifconfig lo inet loopback
		echo "$O" | grep -q '^wlan0:' ||
			ifconfig wlan0 up
		for p in ssd wpa_supplicant dhcpcd; do
			if pgrep -f ^"$p" 1>/dev/null; then
				perrex "$p already running" 1
			fi
		done
		start-stop-daemon \
			--start --background \
			--exec /usr/local/mbin/ssd
		start-stop-daemon \
			--start --background \
			--exec /usr/sbin/dhcpcd \
			-- -q -4 -B -C resolv.conf wlan0
	;;
	stop)
		for p in ssd wpa_supplicant dhcpcd; do
			killall $p || true
		done
	;;
	restart)
		$0 stop
		sleep 5s
		$0 start
	;;
	*) exit 1 ;;
esac
