[[ ! "$-" =~ i ]] && return

HISTCONTROL='ignoredups'
HISTFILE="$HOME/.bashhst"
HISTFILESIZE=999999
HISTSIZE=99999
PS1='$ $?: '

bind "\C-l":clear-screen
bind -r "\C-s"
bind -r "\C-p"
bind "\C-s":vi-movement-mode
bind "\C-x":vi-movement-mode
bind "\C-a":beginning-of-line
bind "\C-e":end-of-line
bind '"\C-n":"nohup st 1>/dev/null 2>&1 &\n"'

set -o vi
shopt -s autocd
shopt -s checkwinsize
shopt -s cmdhist
shopt -s histappend
stty stop ''
ulimit -c 1000

. /usr/subr/dl
. /etc/aliasrc
. "$HOME"/.bashfunc

alias vt="v $HOME/.tasks"
alias vct="v $HOME/.ctasks"
alias vtmp='v /tmp/vtmp'
alias do-diffmgr='find ~/Software/mgit/lancia-utils/* -type f | xargs diffmgr'
alias ytdl-mp3-proxy='youtube-dl --proxy "socks5://$(tpsel)" --extract-audio --audio-format mp3 --audio-quality 0'
alias d='diffmgr *'
